

*** Unable to execute: '"makeindex"  -s "dissertation.ist" -t "dissertation.alg" -o "dissertation.acr" "dissertation.acn"' ***

Failed with error code 139.

Status report:

This is makeindex, version 2.15 [TeX Live 2016] (kpathsea + Thai support).
Scanning style file ./dissertation.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file dissertation.acn....done (154 entries accepted, 0 rejected).

